PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX voc: <https://mmisw.org/ont/~mhoangvslev/SurfaceForestiereVoc/>

CONSTRUCT {

  ?CountryCodeURI a voc:Country;
    voc:hasName ?CountryName;
    voc:hasCountryCode ?CountryCodeRegion;
    voc:ofIncomeGroup ?CountryIncomeGroup.

  ?MeasurementURI a voc:Measurement;
    voc:ofYear ?Year;
    voc:withSurface ?SurfaceForestiere.

  ?CountryCodeURI voc:hasMeasurement ?MeasurementURI
} 
FROM <file:any.csv;encoding=utf-8;delimiter=%3B> 
WHERE {
    # Classify
    BIND( URI(CONCAT("https://mmisw.org/ont/~mhoangvslev/surface_forestiere/", SHA1(CONCAT(?surface_forestiere, ?year)))) as ?MeasurementURI)
    BIND( STRDT(?surface_forestiere, voc:SurfaceForestiere) as ?SurfaceForestiere)
    BIND( STRDT(?year, voc:Year) as ?Year)

    # Localising
    BIND( URI(CONCAT("https://mmisw.org/ont/~mhoangvslev/surface_forestiere/", ?country_code)) as ?CountryCodeURI)
    BIND( STRDT(?country_code, voc:CountryCodeRegion) as ?CountryCodeRegion)
    BIND( STRDT(?country_name, voc:CountryName) as ?CountryName)
    BIND( STRDT(?income_group, voc:CountryIncomeGroup) as ?CountryIncomeGroup)
}
