PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX voc: <https://mmisw.org/ont/~mhoangvslev/SurfaceForestiereVoc/>

CONSTRUCT {
  ?CountryURI a voc:Measurement;
    voc:CountryName ?country_name;
    voc:CountryCodeRegion ?CountryCodeRegion; 
    voc:CountryIncomeGroup ?CountryIncomeGroup;
    voc:Year ?Year;
    voc:SurfaceForestiere ?SurfaceForestiere;
} 
FROM <file:any.csv;encoding=utf-8;delimiter=%3B> 
WHERE {
    # Les groupes de revenu 
    VALUES( ?income_group ?class ){
      ("Revenu élevé" xsd:string)
      ("Revenu intermédiaire, tranche supérieure" xsd:string)
      ("Faible revenu" xsd:string)
      ("Agrégats" xsd:string)
    }

    # Classify
    BIND( URI(CONCAT("https://mmisw.org/ont/~mhoangvslev/surface_forestiere/", SHA1(CONCAT(?country_code, ?year)))) as ?CountryURI)
    BIND( STRDT(?country_code, dbo:isoCodeRegion) as ?CountryCodeRegion)
    BIND( STRDT(?surface_forestiere, xsd:decimal) as ?SurfaceForestiere)
    
    BIND( STRDT(?year, dbo:year) as ?Year)

    # Localising
    BIND( STRLANG(?country_name, "en-EN") as ?CountryName)
    BIND( STRLANG(?income_group, "fr-FR") as ?CountryIncomeGroup)
}
